name: confseq
channels:
  - pyg
  - pytorch
  - nvidia/label/cuda-12.1.1
  - nvidia
  - bioconda
  - conda-forge
  - defaults
  - openbabel
  - pytorch3d
dependencies:
  - python=3.10
  - pip
  - cuda
  - conda-forge::cudnn
  - easydict
  - jupyter
  - gcc=12.1
  - gxx=12.1
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - ninja
  - google-sparsehash
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - openbabel
  - pytorch3d
  - pip:
    - oddt
    - msgpack
    - seaborn
    - lmdb
    - wandb
    - umap-learn
    - epam.indigo
    - py3dmol
    - smilesPE
    - scikit-image
    - torch_geometric
    - transformers
    - accelerate
    - rdkit
    - posebusters
    - timeout_decorator
    - fcd_torch
    - spconv-cu120
    - git+https://github.com/octree-nn/ocnn-pytorch.git
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/Dao-AILab/flash-attention.git
    - ./src/model/pointops